import requests
import streamlit as st
import random

class ImageGenerator:
    def __init__(self):
        # محركات التوليد (يمكن إضافة المزيد مستقبلاً)
        self.base_url = "https://image.pollinations.ai/prompt/"

    def generate_image(self, prompt):
        """توليد صورة بناءً على الوصف"""
        try:
            # تحسين الـ Prompt ليعطي طابع WormGPT (Cyberpunk/Dark)
            enhanced_prompt = f"{prompt}, cyberpunk style, neon red lighting, highly detailed, 8k, digital art, dark atmosphere"
            
            # تنظيف النص ليكون صالحاً كـ URL
            clean_prompt = requests.utils.quote(enhanced_prompt)
            
            # إضافة رقم عشوائي (seed) لضمان عدم تكرار الصور
            seed = random.randint(1, 999999)
            image_url = f"{self.base_url}{clean_prompt}?seed={seed}&width=1024&height=1024&nologo=true"
            
            return image_url
        except Exception as e:
            st.error(f"Image Core Error: {e}")
            return None

    def display_generated_image(self, url):
        """عرض الصورة بشكل احترافي في الشات"""
        if url:
            st.image(url, caption="Neural Art Generated by WormGPT", use_container_width=True)
            # إضافة زر للتحميل
            st.markdown(f'<a href="{url}" download="WormGPT_Art.jpg" style="color:red; text-decoration:none;">[ DOWNLOAD IMAGE ]</a>', unsafe_allow_html=True)
